from inferenceengine.domain.service.inference_motor_service import InferenceMotorService
# from inferenceengine.data.commandrepo.command_repository_mock import CommandRepositoryMock
# from inferenceengine.data.commandrepo.command_repository_petri import CommandRepositoryPetri
from inferenceengine.data.commandrepo.command_repository_ontology import CommandRepositoryOntology
from inferenceengine.domain.entities import *